### ISSUE TITLE
Alternate browser setting doesn't work anymore

### ISSUE THREAD

**Issue by FreeHarry** [PD-Consulting-and-Security/vsc-print#135]
When using an alternate browser like this, it doesn't work anymore:
```
"print.browserPath": "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
```
I get the error message:
<img width="337" alt="2022-06-29_07-59-22--explorer" src="https://user-images.githubusercontent.com/24735031/176362924-c85073a9-4c51-498e-b1f6-24bd25890b67.png">

It was working before V 0.9.18. I never had problems with it.

**Comment by PeterWone** [comment]
Thank you for reporting this. It seems my attempt to make this work for Linux and OSX has caused problems for Linux. I'll sort it out and push an update.

**Comment by PeterWone** [comment]
@FreeHarry this was auto closed when I cross referenced the PR that resolves it. Historically I wait for confirmation from the person who raised an issue before closing it but we're putting in CICD and still getting used to the automation. I manually tested the fix on Windows, so you should be good now, but either way please let me know.

**Comment by FreeHarry** [comment]
I can confirm v0.9.23 solved the problem. Thanks!

**Comment by PeterWone** [comment]
Awesome, now the recruiting pitch: the chap who promised to handle the German translation went quiet a long time ago. Can I interest you in taking it on? Once the settings localisation is done it's an intermittent duty adding small updates to the manual and the readme file.

**Comment by FreeHarry** [comment]
> Awesome, now the recruiting pitch: the chap who promised to handle the German translation went quiet a long time ago. Can I interest you in taking it on? Once the settings localisation is done it's an intermittent duty adding small updates to the manual and the readme file.

Thank you for that invitation! I thought about that, but currently I'm to busy to contribute on the translation. Sorry.
